executionEnvironments: 
  cwc2:
    hci:
      connectionId:           38e854b0-f7d3-4a8f-bf31-2d8bfac3dbd4
      hostName:               'cwc2.bmc.com'
      hostPort:               '16196'
    ces:
      url:                    http://cwc2.bmc.com:2020
    sonar:
      scanner:                Scanner
      server:                 Sonar
      cobolSuffixes:          'cbl,testsuite,testscenario,stub,result,scenario,context'
      copySuffixes:           'cpy'
    xlr:
      template:               'GitFlow/GitFlow_Release'
    jenkins:
      cliPath:                'C:/WorkbenchCLI201501'
    ispw:
      libraryQualifier:         'SALESSUP'
      mfProject:
        rootFolder:             './GenApp_MainframeCore'
        sourcesFolder:          '/Sources'
      configFile:
        folder:                 './GenApp_MainframeCore'
        name:                   'ispwconfig.yml'
      automaticBuildFile:       './automaticBuildParams.txt'
      changedProgramsFile:      './changedPrograms.json'
      branchInfo:
        feature:
          ispwLevel:            FEAT
          mapRule:              per-branch
        hotfix:
          ispwLevel:            HFIX
          mapRule:              per-branch
        release:
          ispwLevel:            RLSE
          mapRule:              per-branch
        main:
          ispwLevel:            PROD
          mapRule:              per-branch
    ttt:
      loadLibQualfiers:
        FEAT:
          level1:               FT1
          level2:               FT1
          level3:               DEVL
          level4:               MAIN
        RLSE:
          level1:               FT2
          level2:               FT2
          level3:               DEVL
          level4:               MAIN
        HFIX:
          level1:               FT3
          level2:               FT3
          level3:               DEVL
          level4:               MAIN
      folders:               
        root:                   'Tests'
        virtualizedTests:       'Unit'
        nonVirtualizedTests:    'Integration'
      environmentIds:
        virtualized:            5c519facfba8720a90ccc645
        nonVirtualized:
          batch:                5c519facfba8720a90ccc645
#          cics:                 5c51a46afba8720a90ccc64d
      results:
        sonar:
          folder:               './TTTSonar'    
          fileNameBase:         'cli.suite.sonar.xml'
        jUnit:
          folder:               '**/TTTUnit'
          fileNameBase:         'cli.suite.junit.xml'
    coco:  
      ccThreshold:              '70'
      results:
        sonar:
          folder:               './Coverage'
          file:                 'CodeCoverage.xml'    
  cwcc:
    hci:
      connectionId:           de2ad7c3-e924-4dc2-84d5-d0c3afd3e756
      hostName:               'cwcc.bmc.com'
      hostPort:               '16196'
    ces:
      url:                    http://cwcc.bmc.com:2020
    sonar:
      scanner:                scanner
      server:                 localhost
      cobolSuffixes:          'cbl,testsuite,testscenario,stub,result,scenario,context'
      copySuffixes:           'cpy'
    xlr:
      template:               'GitFlow/GitFlow_Release'
    jenkins:
      cliPath:                'C:/WB_CLI_201501'
    ispw:
      libraryQualifier:         'SALESSUP'    
      mfProject:
        rootFolder:             './GenApp_MainframeCore'
        sourcesFolder:          '/Sources'
      configFile:
        folder:                 './GenApp_MainframeCore'
        name:                   'ispwconfig.yml'
      automaticBuildFile:       './automaticBuildParams.txt'
      changedProgramsFile:      './changedPrograms.json'
      branchInfo:
        feature:
          ispwLevel:            FEAT
          mapRule:              per-branch
        hotfix:
          ispwLevel:            HFIX
          mapRule:              per-branch
        release:
          ispwLevel:            RLSE
          mapRule:              per-branch
        main:
          ispwLevel:            PROD
          mapRule:              per-branch
    ttt:
      loadLibQualfiers:
        FEAT:
          level1:               FT1
          level2:               FT1
          level3:               DEVL
          level4:               MAIN
        RLSE:
          level1:               FT2
          level2:               FT2
          level3:               DEVL
          level4:               MAIN
        HFIX:
          level1:               FT3
          level2:               FT3
          level3:               DEVL
          level4:               MAIN
      folders:               
        root:                   'Tests'
        virtualizedTests:       'Unit'
        nonVirtualizedTests:    'Integration'
      environmentIds:
        virtualized:            5b508b8a787be73b59238d38
        nonVirtualized:
          batch:                5b508b8a787be73b59238d38
#          cics:                 5b5f2a71787be73b59238d7b
      results:
        sonar:
          folder:               './TTTSonar'    
          fileNameBase:         'cli.suite.sonar.xml'
        jUnit:
          folder:               '**/TTTUnit'
          fileNameBase:         'cli.suite.junit.xml'
    coco:  
      ccThreshold:              '70'
      results:
        sonar:
          folder:               './Coverage'
          file:                 'CodeCoverage.xml'    
  cwc2_on_cwcc:
    hci:
      connectionId:           263438b6-f699-4373-be9f-378af3d28633 #38e854b0-f7d3-4a8f-bf31-2d8bfac3dbd4
      hostName:               'cwc2.bmc.com' #'192.168.96.142'
      hostPort:               '16196'
    ces:
      url:                    http://cwc2.bmc.com:2020 #http://192.168.96.142:2020
    sonar:
      scanner:                scanner
      server:                 localhost
      cobolSuffixes:          'cbl,testsuite,testscenario,stub,result,scenario,context'
      copySuffixes:           'cpy'
    xlr:
      template:               'GitFlow/GitFlow_Release'
    jenkins:
      cliPath:                'C:\WB_CLI_201401' #'C:/TopazCLI201401'
    ispw:
      libraryQualifier:         'SALESSUP'
      mfProject:
        rootFolder:             './GenApp_MainframeCore'
        sourcesFolder:          '/Sources'
      configFile:
        folder:                 './GenApp_MainframeCore'
        name:                   'ispwconfig.yml'
      automaticBuildFile:       './automaticBuildParams.txt'
      changedProgramsFile:      './changedPrograms.json'
      branchInfo:
        feature:
          ispwLevel:            FEAT
          mapRule:              per-branch
        hotfix:
          ispwLevel:            HFIX
          mapRule:              per-branch
        release:
          ispwLevel:            RLSE
          mapRule:              per-branch
        main:
          ispwLevel:            PROD
          mapRule:              per-branch
    ttt:
      loadLibQualfiers:
        FEAT:
          level1:               FT1
          level2:               FT1
          level3:               DEVL
          level4:               MAIN
        RLSE:
          level1:               FT2
          level2:               FT2
          level3:               DEVL
          level4:               MAIN
        HFIX:
          level1:               FT3
          level2:               FT3
          level3:               DEVL
          level4:               MAIN
      folders:               
        root:                   'Tests'
        virtualizedTests:       'Unit'
        nonVirtualizedTests:    'Integration'
      environmentIds:
        virtualized:            5c519facfba8720a90ccc645 #5b508b8a787be73b59238d38
        nonVirtualized:
          batch:                5c519facfba8720a90ccc645 #5b508b8a787be73b59238d38
#          cics:                 5c51a46afba8720a90ccc64d
      results:
        sonar:
          folder:               './TTTSonar'    
          fileNameBase:         'cli.suite.sonar.xml'
        jUnit:
          folder:               '**/TTTUnit'
          fileNameBase:         'cli.suite.junit.xml'
    coco:  
      ccThreshold:              '70'
      results:
        sonar:
          folder:               './Coverage'
          file:                 'CodeCoverage.xml'    
